package com.tcg.rpgengine.input.controller;

public enum VirtualController {
    A, B, X, Y, DPAD_UP, DPAD_DOWN, DPAD_LEFT, DPAD_RIGHT, LEFT_AXIS_X, RIGHT_AXIS_X, LEFT_AXIS_Y, RIGHT_AXIS_Y,
    LEFT_AXIS_BUTTON, RIGHT_AXIS_BUTTON, START, BACK, RIGHT_BUMPER, LEFT_BUMPER, RIGHT_TRIGGER, LEFT_TRIGGER,
    RIGHT_TRIGGER_BUTTON, LEFT_TRIGGER_BUTTON
}
